spring:
  application:
    name: druzhba-hub-app

  config:
    import: optional:file:.env[.properties]

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  data:
    mongodb:
      authentication-database: admin
      database: druzhba-hub
      port: 27017
      host: ${HOST}
    redis:
      host: ${HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  cache:
    type: redis
    cache-names: redis-cache

email:
  address: ${EMAIL_ADDRESS}
  confirm:
    link: http://${HOST}:8080/email/confirm?token=
    token:
      duration: 1440

logging:
  file:
    path: logs
    name: ${logging.file.path}/druzhba-hub-logs.log
  level:
    root: INFO

gcp:
  bucket-name:
    ${GCS_BUCKET_NAME}
  project-id:
    ${GCS_PROJECT_ID}
  credentials:
    file-path:
      ${GCS_CREDENTIALS_PATH}
  api:
    maps:
      key:
        ${GC_MAPS_API_KEY}
jwt:
  secret: ${JWT_SECRET}
  expiration: 1440
